### ISSUE TITLE
Access Token Required to Check Token in changing password

### ISSUE THREAD

**Issue by blade2005** [capless/warrant#14]
Utilizing the develop branch commit a53cb08

In related to #13 I opted to change the code in my file to change my password and encountered the following error:
```
    config = ce.get_config('Cognito', args.configfile)
    u = Cognito(config['pool_id'],config['client_id'], username=args.username)
    response = u.change_password(args.password, args.new_password)

```

```
Traceback (most recent call last):
  File "bin/auth-cognito", line 40, in <module>
    main()
  File "bin/auth-cognito", line 35, in main
    response = u.change_password(args.password, args.new_password)
  File "/home/cdavis/.local/lib/python2.7/site-packages/warrant/__init__.py", line 380, in change_password
    self.check_token()
  File "/home/cdavis/.local/lib/python2.7/site-packages/warrant/__init__.py", line 119, in check_token
    raise AttributeError('Access Token Required to Check Token')
AttributeError: Access Token Required to Check Token
```

If I haven't authenticated how would I have a access token?

**Comment by ebpetway** [comment]
You won't be able to change the user password using change_password in this situation, which is where an admin has created a user with a temporary password.
The way the password will need to be updated is via another respond_to_auth boto3 client call, like so:
```python
tokens = boto_client.respond_to_auth_challenge(
    ClientId='client_id',
    ChallengeName='NEW_PASSWORD_REQUIRED',
    Session='session_string_from_first_challenge_response',
    ChallengeResponses={
        'NEW_PASSWORD': 'new_password',
        'USERNAME': 'username'
    }
)
```

**Comment by blade2005** [comment]
Ohhh. So it more directly ties back into #13 alright. Thanks.
