### ISSUE TITLE
How to register a user? develop, python 3

### ISSUE THREAD

**Issue by armicron** [capless/warrant#69]
I've checked out a `develop` branch and tried to register a user.
```python
from warrant import Cognito

u = Cognito("us-east-xxxxI", "zzzzzzzzz", client_secret="yyyyy")
u.add_base_attributes(email='test@gmail.com')
u.add_custom_attributes(state='virginia', city='Centreville')
u.register(username='xxx', password='qwerty234@$')
```
I've got a TypeError
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arm/coding/python/cognito/warrant/warrant/__init__.py", line 303, in register
    attributes= dict(self.base_attributes.items() + self.custom_attributes.items())
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
```
```
Tested with two versions of python.
python -V
Python 3.4.5
python -V
Python 3.6.1
```
Seems that [the code](https://github.com/capless/warrant/pull/66) is tested only for python 2.7 and why not to update a Readme?

**Comment by koorukuroo** [comment]
There are same error.

```
u.add_base_attributes(email=USERNAME)
u.add_custom_attributes(state='virginia', city='Centreville')
res = u.register(USERNAME, PASSWORD)
```

I've got other TypeError

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-1104a483b338> in <module>()
     14 u.add_base_attributes(email='test@gmail.com')
     15 u.add_custom_attributes(state='virginia', city='Centreville')
---> 16 u.register(username='xxx', password='qwerty234@$')

~/anaconda3/envs/A/lib/python3.6/site-packages/warrant/__init__.py in register(self, username, password, attr_map)
    308             'UserAttributes': cognito_attributes
    309         }
--> 310         self._add_secret_hash(params, 'SecretHash')
    311         response = self.client.sign_up(**params)
    312 

~/anaconda3/envs/A/lib/python3.6/site-packages/warrant/__init__.py in _add_secret_hash(self, parameters, key)
    626         if self.client_secret is not None:
    627             secret_hash = AWSSRP.get_secret_hash(self.username, self.client_id,
--> 628                                                  self.client_secret)
    629             parameters[key] = secret_hash
    630 

~/anaconda3/envs/A/lib/python3.6/site-packages/warrant/aws_srp.py in get_secret_hash(username, client_id, client_secret)
    169     @staticmethod
    170     def get_secret_hash(username, client_id, client_secret):
--> 171         message = bytearray(username + client_id, 'utf-8')
    172         hmac_obj = hmac.new(bytearray(client_secret, 'utf-8'), message, hashlib.sha256)
    173         return base64.standard_b64encode(hmac_obj.digest()).decode('utf-8')

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
