### ISSUE TITLE
pip install: ImportError: No module named 'pip.req'

### ISSUE THREAD

**Issue by strk** [capless/warrant#96]
```
~$ pip --version
pip 10.0.0b2 from /usr/local/lib/python3.4/dist-packages/pip-10.0.0b2-py3.4.egg/pip (python 3.4)
~$ pip install --user warrant-ext
Collecting warrant-ext
  Using cached warrant-ext-0.2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i1hxw5f7/warrant-ext/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-i1hxw5f7/warrant-ext/
```

**Comment by strk** [comment]
`pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)` successfully installs warrant-ext so I guess this issue should go to pip, not here...

**Comment by bjinwright** [comment]
This is fixed in develop and will be in v0.7.
